const GROCERY_SEARCH_MAP: Record<string, string> = {
  "all-purpose flour": "all purpose flour 5lb",
  "bread flour": "bread flour 5lb",
  "cake flour": "cake flour",
  "self-rising flour": "self rising flour",
  "whole wheat flour": "whole wheat flour 5lb",

  "granulated white sugar": "granulated sugar 4lb",
  "light brown sugar": "brown sugar",
  "powdered (confectioners') sugar": "powdered sugar",
  "caster (superfine) sugar": "superfine sugar",

  "unsalted butter": "unsalted butter",
  "salted butter": "salted butter",

  "vegetable oil": "vegetable oil 48oz",
  "extra-virgin olive oil": "extra virgin olive oil",
  "canola oil": "canola oil",
  "toasted sesame oil": "sesame oil",
  "virgin coconut oil": "coconut oil",

  "whole milk": "whole milk gallon",
  "skim milk": "skim milk gallon",
  "heavy cream (35% fat)": "heavy cream",
  "heavy whipping cream": "heavy whipping cream",
  "half-and-half cream": "half and half",
  "sour cream": "sour cream 16oz",
  "plain whole-milk yogurt": "plain yogurt",
  "plain Greek yogurt": "greek yogurt",
  "buttermilk": "buttermilk",

  "sharp cheddar cheese": "cheddar cheese",
  "cheddar cheese": "cheddar cheese",
  "fresh mozzarella cheese": "mozzarella cheese",
  "Parmigiano-Reggiano cheese": "parmesan cheese",
  "cream cheese": "cream cheese 8oz",
  "ricotta cheese": "ricotta cheese",
  "feta cheese": "feta cheese",
  "aged gouda cheese": "gouda cheese",
  "Gruyère cheese": "gruyere cheese",
  "brie cheese": "brie cheese",
  "soft goat cheese (chèvre)": "goat cheese",
  "mascarpone cheese": "mascarpone cheese",

  "large egg": "eggs dozen",
  "large eggs": "eggs dozen",

  "fine sea salt": "sea salt",
  "kosher salt (Diamond Crystal)": "kosher salt",
  "fine table salt": "table salt",
  "freshly ground black pepper": "black pepper",

  "long-grain white rice": "white rice",
  "long-grain brown rice": "brown rice",
  "basmati rice": "basmati rice",
  "jasmine rice": "jasmine rice",
  "arborio rice (risotto)": "arborio rice",

  "dried pasta (spaghetti)": "spaghetti pasta",
  "dried spaghetti": "spaghetti",
  "dried penne rigate": "penne pasta",
  "dried linguine": "linguine pasta",
  "dried fettuccine": "fettuccine pasta",
  "dried rigatoni": "rigatoni pasta",
  "dried elbow macaroni": "elbow macaroni",
  "egg noodles": "egg noodles",
  "ramen noodles": "ramen noodles",

  "boneless skinless chicken breast": "chicken breast",
  "bone-in chicken thigh": "chicken thighs",
  "bone-in chicken thighs": "chicken thighs",
  "ground chicken": "ground chicken",

  "beef chuck roast": "beef chuck roast",
  "ground beef (80/20)": "ground beef",
  "ribeye steak": "ribeye steak",
  "pork loin": "pork loin",
  "ground pork": "ground pork",
  "bone-in pork chop": "pork chops",
  "bone-in pork chops": "pork chops",
  "thick-cut bacon": "bacon",
  "Italian pork sausage": "italian sausage",
  "lamb leg": "lamb leg",
  "ground lamb": "ground lamb",
  "ground turkey (93% lean)": "ground turkey",
  "turkey breast": "turkey breast",
  "smoked ham": "smoked ham",
  "prosciutto di Parma": "prosciutto",
  "diced pancetta": "pancetta",
  "guanciale": "guanciale",

  "Atlantic salmon fillet": "salmon fillet",
  "large raw shrimp, peeled & deveined": "shrimp",
  "large raw prawns, peeled & deveined": "raw prawns",
  "fresh tuna steak": "tuna steak",
  "fresh cod fillet": "cod fillet",
  "tilapia fillet": "tilapia fillet",
  "halibut fillet": "halibut fillet",
  "dry-packed sea scallops": "sea scallops",

  "fresh garlic": "garlic",
  "yellow onion": "yellow onion",
  "yellow onions": "yellow onions",
  "red onion": "red onion",
  "shallot": "shallots",
  "shallots": "shallots",
  "green onion (scallion)": "green onions",
  "green onions (scallions)": "green onions",
  "scallion": "green onions",
  "scallions": "green onions",
  "fresh ginger root": "fresh ginger",
  "fresh lemon": "lemons",
  "fresh lemons": "lemons",
  "fresh lime": "limes",
  "fresh limes": "limes",

  "vine-ripened tomato": "tomatoes",
  "vine-ripened tomatoes": "tomatoes",
  "cherry tomatoes": "cherry tomatoes",
  "canned whole peeled tomatoes": "canned tomatoes",
  "double-concentrated tomato paste": "tomato paste",
  "canned tomato sauce": "tomato sauce",

  "russet potato": "russet potatoes",
  "russet potatoes": "russet potatoes",
  "sweet potato": "sweet potatoes",
  "sweet potatoes": "sweet potatoes",

  "carrot": "carrots",
  "carrots": "carrots",
  "celery stalks": "celery",
  "bell pepper": "bell pepper",
  "broccoli crown": "broccoli",
  "cauliflower": "cauliflower",
  "fresh baby spinach": "baby spinach",
  "lacinato kale": "kale",
  "romaine lettuce": "romaine lettuce",
  "green cabbage": "green cabbage",
  "cremini mushrooms": "mushrooms",
  "zucchini": "zucchini",
  "eggplant": "eggplant",
  "ripe Hass avocado": "avocado",
  "ripe Hass avocados": "avocados",
  "English cucumber": "cucumber",
  "sweet corn": "corn",
  "fresh asparagus": "asparagus",

  "fresh cilantro": "cilantro",
  "fresh flat-leaf parsley": "parsley",
  "fresh basil": "fresh basil",
  "fresh rosemary": "fresh rosemary",
  "fresh thyme": "fresh thyme",
  "fresh dill": "fresh dill",
  "fresh mint": "fresh mint",
  "fresh sage": "fresh sage",
  "fresh chives": "fresh chives",
  "dried oregano": "dried oregano",
  "dried bay leaf": "bay leaves",
  "dried bay leaves": "bay leaves",

  "ground cumin": "ground cumin",
  "sweet paprika": "paprika",
  "smoked paprika (pimentón)": "smoked paprika",
  "ground cinnamon": "ground cinnamon",
  "whole nutmeg": "nutmeg",
  "ground turmeric": "turmeric",
  "cayenne pepper": "cayenne pepper",
  "chili powder": "chili powder",
  "curry powder": "curry powder",
  "crushed red pepper flakes": "red pepper flakes",
  "garlic powder": "garlic powder",
  "onion powder": "onion powder",
  "Italian seasoning blend": "italian seasoning",

  "low-sodium soy sauce": "soy sauce",
  "white distilled vinegar": "white vinegar",
  "balsamic vinegar of Modena": "balsamic vinegar",
  "raw apple cider vinegar": "apple cider vinegar",
  "seasoned rice vinegar": "rice vinegar",
  "red wine vinegar": "red wine vinegar",
  "hot sauce": "hot sauce",
  "Worcestershire sauce": "worcestershire sauce",
  "fish sauce": "fish sauce",
  "oyster sauce": "oyster sauce",
  "sriracha hot chili sauce": "sriracha",
  "Dijon mustard": "dijon mustard",
  "tomato ketchup": "ketchup",
  "mayonnaise": "mayonnaise",

  "raw honey": "honey",
  "pure maple syrup": "maple syrup",
  "pure vanilla extract": "vanilla extract",

  "double-acting baking powder": "baking powder",
  "baking soda (bicarbonate)": "baking soda",
  "active dry yeast": "active dry yeast",
  "cornstarch (corn flour)": "cornstarch",
  "unsweetened cocoa powder": "cocoa powder",
  "semi-sweet chocolate": "baking chocolate",
  "semi-sweet chocolate chips": "chocolate chips",
  "unflavored gelatin powder": "gelatin",

  "low-sodium chicken broth": "chicken broth",
  "chicken stock": "chicken stock",
  "low-sodium beef broth": "beef broth",
  "beef stock": "beef stock",
  "vegetable broth": "vegetable broth",

  "crusty sourdough bread": "sourdough bread",
  "flour tortilla (10-inch)": "flour tortillas",
  "flour tortillas (10-inch)": "flour tortillas",
  "pita bread": "pita bread",
  "naan bread": "naan bread",

  "canned black beans, drained": "black beans canned",
  "canned chickpeas, drained": "chickpeas canned",
  "dried green lentils": "lentils",
  "canned kidney beans, drained": "kidney beans canned",
  "canned cannellini beans, drained": "cannellini beans canned",

  "full-fat coconut milk": "coconut milk",
  "unsweetened almond milk": "almond milk",
  "oat milk": "oat milk",

  "extra-firm tofu": "tofu",
  "tempeh": "tempeh",

  "creamy peanut butter": "peanut butter",
  "almond butter": "almond butter",
  "tahini (sesame paste)": "tahini",

  "dry white wine": "white wine cooking",
  "dry red wine": "red wine cooking",

  "walnut halves": "walnuts",
  "whole almonds": "almonds",
  "pecan halves": "pecans",
  "pine nuts": "pine nuts",
  "raw cashews": "cashews",
  "roasted peanuts": "peanuts",
};

export function getGrocerySearchTerm(ingredientName: string): string {
  const mapped = GROCERY_SEARCH_MAP[ingredientName];
  if (mapped) {
    console.log(`[GrocerySearch] "${ingredientName}" → "${mapped}"`);
    return mapped;
  }

  const cleaned = ingredientName
    .toLowerCase()
    .replace(/[()''""]/g, "")
    .replace(/\s+/g, " ")
    .trim();

  console.log(`[GrocerySearch] No mapping for "${ingredientName}", using: "${cleaned}"`);
  return cleaned;
}
